### ISSUE TITLE
V3 explanation

### ISSUE THREAD

**Issue by StevenGubkin** [TeamBasedInquiryLearning/linear-algebra#181] opened 2021-07-06 13:38 UTC
While exploring the reasoning behind V3 in class, we row reduced some matrices using b = <b_1, b_2, b_3, ..., b_n> as the "target vector".  We saw that if the RREF of the matrix of vectors had a row of zeros, then this would give a relation on the b variables, and so some choice of b would lead to an inconsistent system.

One student wondered whether it was possible that, while row reducing this "general augmented matrix", the variables could all cancel out and you would end up with a row of zeros with a zero also in the "augmented column".  If that happened, then the system would be consistent!

This is a good question.

An easy fix is to explicitly name a vector which will not be in the span:  if the first row of zeros in RREF(A) happens in row j, then the jth standard basis vector is not in the span of the columns of a.  The reason is that if you track through the Gauss-Jordan algorithm on the augmented matrix, the row operations needed to create that first row of zeros do not alter the augmented column at all.  You are adding a linear combination of the first (j-1) rows to the jth row, and those (j-1) rows are all zero in the augmented column.  So RREF(A) will have a row of zeros with an augmented 1, which demonstrates that the jth standard basis vector is not in the span.

This seems better than just stating that "some vector will work".  It gets students to think about the algorithm again in a more general setting, and it reframes the algorithm using the new vocabulary of "linear combinations" of the rows (which they have just learned).

**Comment by siwelwerd** [comment] 2021-07-06 13:41
Which activity is this in reference to?

**Comment by StevenGubkin** [comment] 2021-07-06 13:48
It is referring to the explanation of V3 in the textbook:

https://teambasedinquirylearning.github.io/linear-algebra/V3.html

It is stated as a "fact" without any reasoning.  The activity of row
reducing using a "general vector" <b_1, b_2, ..., b_n> was a students idea
for trying to see what the "fact" was true.  The class was almost able to
convince itself of the "fact", but couldn't explain why it was impossible
for row reduction augmenting with this general vector to result in a 0 in
the augmented column.  We then realized that instead of using a general
vector, we could just use the jth standard basis vector as an explicit
choice of vector not in the span.

**Comment by siwelwerd** [comment] 2021-07-06 13:59
Fact 2.3.10?  Yeah, it's a little hand-wavy at the moment. 

I think the appeal of saying "some vector" is that it removes the emphasis from finding what that particular vector is.  I'll leave this open until I get a more detailed explanation added in there.

Sometimes choices were made to limit things presented on slides (to not overload the slides) before there was ever a "textbook" version. I think we want to go back and add some of these as "asides" that show up in the textbook but not the slides.

**Comment by siwelwerd** [comment] 2022-12-21 18:23
I wrote a new activity in [Activity 2.3.5](https://teambasedinquirylearning.github.io/linear-algebra/2023/VS3.html#activity-44) 
to try and help this.  Closing for now, but happy to revisit this depending on how that works with students in the spring.

**Comment by StevenClontz** [comment] 2023-02-07 17:37
This rewrite fell flat in class last week, so I rewrote it as this:

![image](https://user-images.githubusercontent.com/1559632/217321492-e7cf1bed-29d2-4a02-8eaf-b69cf23cdcc6.png)

![image](https://user-images.githubusercontent.com/1559632/217321522-02e9ddc5-2e42-4c57-b291-e961b498d250.png)

I'm working on a few tweaks (watch updates at https://teambasedinquirylearning.github.io/linear-algebra/2023/EV2.html ), but things certainly worked better for me at least with this alternative take.

I'm going to catch up on this thread now...

**Comment by StevenClontz** [comment] 2023-02-07 17:55
I changed (c) as follows in 7574392

![image](https://user-images.githubusercontent.com/1559632/217323999-b841e5a8-cc1e-4481-82c7-ca1021208212.png)

I did have a student ask "what if the ? is a 0" but it was quickly set aside by pointing out that this isn't the issue: the issue is that it *could* be a 1, and by reversing row operations we get a witnessing vector that causes the RREF to have a contradiction.

**Comment by StevenClontz** [comment] 2023-05-04 20:09
Leaving this open until the fall when it gets use in the full 2023 edition.

**Comment by siwelwerd** [comment] 2023-10-04 17:22
Feedback in Slack based on this semester's implementation is positive, so closing this. Additional improvements can of course still be submitted as PRs.

**Closed by siwelwerd** 2023-10-04 17:22 UTC
